---
- name: Playbook to deploy Demo
  vars:
    terraform_template_vars: "{{ playbook_dir }}/group_vars/terraform.template.tfvars"
    credentials_template_vars: "{{ playbook_dir }}/group_vars/credentials.auto.template.tfvars"
    shared_outputs_vars: "{{ playbook_dir }}/group_vars/shared_outputs.json"
    shared_outputs_template: "{{ playbook_dir }}/shared_outputs_template.j2" 
  hosts: localhost
  pre_tasks:
    - name: Create shared outputs file if doesn't exist
      copy:
        dest: "{{ shared_outputs_vars }}"
        force: false
        content: {}
      check_mode: no
  roles:
    - role: 101-azure-vnet-std
    - role: 220-dev-tools
    - role: 280-integration-platform-multicloud
    - role: 350-data-hub-connection
    - role: 350-data-lake-connection
    - role: 350-oracle-database-connection
    - role: 350-salesforce-connection
    - role: 540-aks-container-deployment