apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 350-data-lake-connection
  labels:
    type: software
    platform: azure
    code: '350'
  annotations:
    displayName: Data Lake Connection
    description: Data Lake Connection
    vpn/required: false
spec:
  version: v1.0.0
  modules:
    - name: data-lake-connection
      alias: data-lake-connection
      version: v1.0.0
  variables:
    - name: data-lake-connection_name
      type: string
      description: The name of the Data Lake connection
    - name: region
      type: string
      description: The Azure location where the resource group will be provisioned
    - name: subscription_id
      type: string
    - name: client_id
      type: string
    - name: client_secret
      type: string
      sensitive: true
    - name: tenant_id
      type: string
